### ISSUE TITLE
Разработать компонент фич 3 спринта: компонент Счетчик на странице проекта

### ISSUE THREAD

**Issue by kseniia2673** [Pet-projects-CodePET/Frontend#103]
Разработать компонент счетчака из UI-kit
![2024-03-19_16-38-35](https://github.com/Pet-projects-CodePET/Frontend/assets/118973229/ff5accd5-fa06-410f-be47-78f953a1c6f7)

**Comment by Julia-Papina** [comment]
Выполнено
