### ISSUE TITLE
Сверстать фичу LK.4.10 Просмотр заявок на проект (участник)+ LK.4.10.1 удаление заявок на проект 

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Frontend#188]
Ссылка на требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.dsrrpknrwmui

Ссылка на фигму:
https://www.figma.com/file/OkJgqsGOL7OKB2agjVMcST/CodePET?type=design&node-id=4652-163931&mode=design&t=3ddOAUFv5gwt3waQ-0

- [x]  десктоп
- [x]  планшет
- [x]  мобилка

![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/32541462/25a7a4e9-9e51-4d60-a729-9fe85a5d73b6)
![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/32541462/ce0ed5a6-732c-4fa8-a4d5-595de1012e9a)

**Comment by Julia-Papina** [comment]
Выполнено
