### ISSUE TITLE
Разработать фичу фичу LK.4.10 Просмотр заявок на проект (участник)+ LK.4.10.1 удаление заявок на проект

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Frontend#189]
Ссылка на требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.dsrrpknrwmui

Ссылка на фигму:
https://www.figma.com/file/OkJgqsGOL7OKB2agjVMcST/CodePET?type=design&node-id=4652-163931&mode=design&t=3ddOAUFv5gwt3waQ-0

**Comment by Julia-Papina** [comment]
Выполнено
