### ISSUE TITLE
Сверстать фичу P.5.5 Подача заявок на участие в проекте

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Frontend#190]
Ссылка на требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.djtsibc5skr

Ссылка на фигму:
https://www.figma.com/file/OkJgqsGOL7OKB2agjVMcST/CodePET?type=design&node-id=4620-156002&mode=design&t=3ddOAUFv5gwt3waQ-0

- [x]  десктоп
- [x]  планшет
- [x]  мобилка

![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/32541462/b4b27655-5019-4819-a5ce-523f7cc16c5d)
![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/32541462/c4b41e3a-540d-4208-a71e-7cf7985019b9)
![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/32541462/ebce0ff9-acbc-4691-98e5-67a9b6b2df91)

**Comment by Julia-Papina** [comment]
Выполнено
