### ISSUE TITLE
Разработать фичу P.5.5 Подача заявок на участие в проекте

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Frontend#191]
Ссылка на требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.djtsibc5skr

Ссылка на фигму:
https://www.figma.com/file/OkJgqsGOL7OKB2agjVMcST/CodePET?type=design&node-id=4620-156002&mode=design&t=3ddOAUFv5gwt3waQ-0

**Comment by Julia-Papina** [comment]
Выполнено
