### ISSUE TITLE
Доработать верстку страницы авторизации/регистрации/восстановления пароля

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Frontend#212]
Необходимо переработать верстку страниц авторизации, регистрации и восстановления пароля, чтобы формы всегда оставались по центру экрана вне зависимости от ширины окна браузера.

https://github.com/Pet-projects-CodePET/Frontend/assets/32541462/7ab959ff-e4cb-49d2-809b-e2af03ec7a6b

**Comment by Julia-Papina** [comment]
Выполнено
