### ISSUE TITLE
Разработать фичу P.5.8 Добавление/удаление проектов из избранного

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Frontend#241]
![Image](https://github.com/user-attachments/assets/bce5581e-7aeb-4c20-b357-ab4e5f29fe78)
![Image](https://github.com/user-attachments/assets/e04965cb-fdbd-49ca-9458-6909c79437fd)
![Image](https://github.com/user-attachments/assets/48a844ed-a8a3-43ad-bd58-11372296493b)

![Image](https://github.com/user-attachments/assets/cf674177-067e-42c7-8ea8-3b5aa013683d)

![Image](https://github.com/user-attachments/assets/3aad68f3-405b-477e-969d-50b5b18fba98)

**Comment by Julia-Papina** [comment]
Выполнено
