### ISSUE TITLE
Сверстать фичу LK.4.12  Просмотр избранных проектов

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Frontend#242]
https://www.figma.com/design/OkJgqsGOL7OKB2agjVMcST/CodePET?node-id=4706-203343&t=jdFqnUebEKMNeb5n-0
https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.2nyyv31mi5oi
![Image](https://github.com/user-attachments/assets/9cae7b88-734e-4f33-b4ae-bc91858a1cdb)
![Image](https://github.com/user-attachments/assets/74526dca-1c68-4ff7-b9d6-97f098f40f6a)
![Image](https://github.com/user-attachments/assets/ba7543f8-4861-4af9-954f-e4725544d0ec)

**Comment by Julia-Papina** [comment]
Выполнено
