### ISSUE TITLE
Разработать фичу LK.4.12 Просмотр избранных проектов

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Frontend#243]
https://www.figma.com/design/OkJgqsGOL7OKB2agjVMcST/CodePET?node-id=4706-203343&t=jdFqnUebEKMNeb5n-0
https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.2nyyv31mi5oi
![Image](https://github.com/user-attachments/assets/b325f647-cf16-4a43-bbf8-e5cea4c91712)
![Image](https://github.com/user-attachments/assets/d115a860-6d26-4f20-99c0-0e4dbdb54fcc)
Избранные проекты у авторизованного пользователя доступны в ручке:
![Image](https://github.com/user-attachments/assets/83fb3a6c-f008-420e-a036-8d67bc2f4c3b)
Нужно применить фильтр:
![Image](https://github.com/user-attachments/assets/b7c3ef82-3f09-41bc-a40f-6d21af3b52dd)

![Image](https://github.com/user-attachments/assets/77d58354-ee4d-4c24-ae20-75e7ad6998cd)

**Comment by Julia-Papina** [comment]
Выполнено
