### ISSUE TITLE
Разработать фичу G.1.1 Просмотр главной страницы

### ISSUE THREAD

**Issue by kseniia2673** [Pet-projects-CodePET/Frontend#26]
См. требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit

- [x] Реализовать логику со стороны фронта и бека

Настроить получение информации с бекенда
- [x] тексты на главной
- [x] проекты
- [x] счетчики проектов и участников

**Comment by Julia-Papina** [comment]
Выполнено
