### ISSUE TITLE
Разработать фичу V.3.1 Авторизация по email

### ISSUE THREAD

**Issue by kseniia2673** [Pet-projects-CodePET/Frontend#27]
См. требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit

- [x] Реализовать логику со стороны фронта и бека

Настроить получение информации с бекенда
- [x] проверять что пользователь с таким паролем и почтой существует

**Comment by Julia-Papina** [comment]
Выполнено
