### ISSUE TITLE
Разработать фичу V.3.3 восстановление пароля

### ISSUE THREAD

**Issue by kseniia2673** [Pet-projects-CodePET/Frontend#28]
1. Настроить получение информации с бекенда
- [x] проверка что почта существует в БД

См. требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit
При успешно пройденной проверке e-mail в БД:
1. на электронную почту поступает сгенерированный пароль;
2. под полем ввода “E-mail” появляется поле ввода “Пароль”;
3. в форме “Восстановление пароля” текст: “На ваш e-mail был отправлен новый пароль”;
4. Кнопка “Восстановить пароль” переименовывается на кнопку “Войти”;
 и тд.

**Comment by Julia-Papina** [comment]
Выполнено
