### ISSUE TITLE
Разработать фичу R.2.1 регистрация пользователя по email

### ISSUE THREAD

**Issue by kseniia2673** [Pet-projects-CodePET/Frontend#29]
См. требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit

1. Подключить бекенд
- [x] настроить отправку информации на бекенд
- [x] настроить подтверждение почты
- [ ] настроить авторизацию пользователя при переходе по ссылке отправленной на почту 

Из требований:
1. При успешной валидации, на электронный адрес, указанный при регистрации, отправляется письмо с ссылкой для авторизации.
2. При переходе по ссылке из письма, аккаунт активируется, пользователь становится авторизованным

**Comment by Julia-Papina** [comment]
Выполнено
