### ISSUE TITLE
Разработать фичу V.3.3 восстановление пароля

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Frontend#3]
Ссылка на фич лист:
https://docs.google.com/spreadsheets/d/1QXD36DZHGH-bGDUzqYXv3B9DDxJkbzYI0FapSGFM5vk/edit#gid=765184209

1. Сверстать страницу в нескольких разрешениях 
- [ ] десктоп
- [ ] планшет
- [ ] мобилка

**Comment by Julia-Papina** [comment]
Выполнено
