### ISSUE TITLE
Разработать фичу LK.4.1 Просмотр личного кабинета

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Frontend#33]
Ссылка на фич лист:
https://docs.google.com/spreadsheets/d/1QXD36DZHGH-bGDUzqYXv3B9DDxJkbzYI0FapSGFM5vk/edit#gid=765184209

Сверстать страницу в нескольких разрешениях

- [x] десктоп
- [x]  планшет
- [x] мобилка

Тут необходимо сделать страничку со всеми табами, по тем табам на которые у нас сейчас нет экранов, делаем заглушки. Активными будут только первые 2 таба: профиль и управление аккаунтом

![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/146813902/68820843-0d9d-4fc9-92fb-b6b8672916c0)

**Comment by Julia-Papina** [comment]
выполнено
