### ISSUE TITLE
Разработать фичу LK.4.2, LK.4.2.1 Редактирование профиля пользователя

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Frontend#34]
Ссылка на фич лист:
https://docs.google.com/spreadsheets/d/1QXD36DZHGH-bGDUzqYXv3B9DDxJkbzYI0FapSGFM5vk/edit#gid=765184209

LK.4.2.1 Редактирование профиля пользователя

Сверстать страницу в нескольких разрешениях

- [x] десктоп
- [x]  планшет
- [x] мобилка

![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/146813902/1b57be84-3a4c-4234-ae67-cbf8488bd9cd)

**Comment by Julia-Papina** [comment]
выполнено
