### ISSUE TITLE
Разработать фичи P.5.1, P.5.2, P.5.7 (превью проектов, пагинация, фильтры)

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Frontend#35]
Ссылка на фич лист:
https://docs.google.com/spreadsheets/d/1QXD36DZHGH-bGDUzqYXv3B9DDxJkbzYI0FapSGFM5vk/edit#gid=765184209

Задача включает себя страницу состоящую из нескольких фич:
- P.5.1 Просмотр превью проектов
- P.5.2 Пагинация в разделе проектов
- P.5.7 Фильтрация проектов

</body>
</html>
Сверстать страницу в нескольких разрешениях
 

- [ ] десктоп
- [ ]  планшет
- [ ] мобилка

![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/146813902/7321edc4-b491-47be-9731-0a0525f93b1d)

**Comment by Julia-Papina** [comment]
Выполнено
