### ISSUE TITLE
Разработать P.5.7 Фильтрация проектов

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Frontend#37]
Ссылка на фич лист:
https://docs.google.com/spreadsheets/d/1QXD36DZHGH-bGDUzqYXv3B9DDxJkbzYI0FapSGFM5vk/edit#gid=765184209

Сверстать страницу в нескольких разрешениях
 

- [x] десктоп
- [x]  планшет
- [x] мобилка
![2024-02-15_21-04-43](https://github.com/Pet-projects-CodePET/Frontend/assets/118973229/879acd73-25f1-4c92-ab01-61dfa01f6124)

**Comment by Julia-Papina** [comment]
Выполнено
