### ISSUE TITLE
Разработать фичу V.3.1 Авторизация по email

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Frontend#5]
Ссылка на фич лист:
https://docs.google.com/spreadsheets/d/1QXD36DZHGH-bGDUzqYXv3B9DDxJkbzYI0FapSGFM5vk/edit#gid=765184209

1. Сверстать главную страницу в нескольких разрешениях 
- [ ] десктоп
- [ ] планшет
- [ ] мобилка

3. Настроить роуты при клике по кнопкам

**Comment by Julia-Papina** [comment]
Выполнено
