### ISSUE TITLE
Разработать фичу S.6.6 Фильтрация специалистов

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Frontend#51]
Ссылка на требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.nkhtrjnb54ni

Ссылка на фигму: https://www.figma.com/file/OkJgqsGOL7OKB2agjVMcST/CodePET?type=design&node-id=68-2&mode=design&t=JNqMgbE6ADRuv79S-0

- [ ] десктоп
- [ ] планшет
- [ ] мобилка

![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/146813902/992c6623-d39b-4a74-a416-26aa862afb8c)

**Comment by Julia-Papina** [comment]
Выполнено
