### ISSUE TITLE
Сверстать страницу специалистов: S.6.1 Превью специалистов + S.6.2 Пагинация в разделе специалистов + S.6.6 Фильтрация специалистов

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Frontend#53]
Ссылка на требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.nkhtrjnb54ni

Ссылка на фигму: https://www.figma.com/file/OkJgqsGOL7OKB2agjVMcST/CodePET?type=design&node-id=68-2&mode=design&t=JNqMgbE6ADRuv79S-0

- [ ] десктоп
- [ ] планшет
- [ ] мобилка

![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/146813902/af8d346f-f049-4420-9811-b8f5a6d1a211)

**Comment by Julia-Papina** [comment]
Выполнено
