### ISSUE TITLE
Разработать фичу S.6 Специалисты (поиск людей в команду)

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Frontend#54]
Ссылка на требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.nkhtrjnb54ni

- [ ] десктоп
- [ ] планшет
- [ ] мобилка

**Comment by Julia-Papina** [comment]
Выполнено (верстка)
