### ISSUE TITLE
Сверстать страницу P.5.3 Просмотр детальной страницы проекта

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Frontend#56]
Ссылка на требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.nkhtrjnb54ni

Ссылка на фигму: https://www.figma.com/file/OkJgqsGOL7OKB2agjVMcST/CodePET?type=design&node-id=68-2&mode=design&t=JNqMgbE6ADRuv79S-0

- [x] десктоп
- [x] планшет
- [x] мобилка

![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/146813902/b98824ef-73ee-41a0-9d45-08fba22d1709)

**Comment by Julia-Papina** [comment]
Выполнено
