### ISSUE TITLE
Разработать фичу R.2.1 регистрация пользователя по email

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Frontend#6]
Ссылка на фич лист:

https://docs.google.com/spreadsheets/d/1QXD36DZHGH-bGDUzqYXv3B9DDxJkbzYI0FapSGFM5vk/edit#gid=765184209

1. Сверстать главную страницу в нескольких разрешениях 
- [ ] десктоп
- [ ] планшет
- [ ] мобилка

**Comment by Julia-Papina** [comment]
Компонент формы - @VanVorobyov
