### ISSUE TITLE
Разработать фичу LK.4.2 LK.4.2.2 Управление аккаунтом пользователя

### ISSUE THREAD

**Issue by kseniia2673** [Pet-projects-CodePET/Frontend#60]
Ссылка на фич лист:
https://docs.google.com/spreadsheets/d/1QXD36DZHGH-bGDUzqYXv3B9DDxJkbzYI0FapSGFM5vk/edit#gid=765184209

Данная фича также включает в себя фичу LK.4.2.2.1 Изменение пароля

Разработать компонент Toggle Checkbox

Сверстать страницу в нескольких разрешениях

- [x] десктоп
- [x]  планшет
- [x] мобилка

![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/146813902/9285563a-4e27-44f1-b019-80fee38fd24c)

**Comment by Julia-Papina** [comment]
Выполнено
