### ISSUE TITLE
Разработать фичу LK.4.1 Просмотр личного кабинета

### ISSUE THREAD

**Issue by kseniia2673** [Pet-projects-CodePET/Frontend#61]
![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/146813902/9d9116fb-2a6c-4c1f-acb7-a80d0e3cb812)

Подключить логику по фиче: сделать табы кликабельными. Пока доступны только табы: профиль и управление аккаунтом. На остальные табы поставить заглушки

Требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit

Дизайн: https://www.figma.com/file/OkJgqsGOL7OKB2agjVMcST/CodePET?type=design&node-id=3109-82272&mode=design&t=3JHm9tvApAC1UOiw-0

**Comment by Julia-Papina** [comment]
Выполнено
