### ISSUE TITLE
Разработать фичу LK.4.2, LK.4.2.1 Редактирование профиля пользователя

### ISSUE THREAD

**Issue by kseniia2673** [Pet-projects-CodePET/Frontend#62]
Необходимо прикрутить логику к редактированию профиля

![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/146813902/75f1d7f1-b581-4592-9c7d-9fe1220d3b32)

**Comment by Julia-Papina** [comment]
Выполнено
