### ISSUE TITLE
Разработать фичи P.5.1, P.5.2 (превью проектов, пагинация)

### ISSUE THREAD

**Issue by kseniia2673** [Pet-projects-CodePET/Frontend#63]
![Image](https://github.com/Pet-projects-CodePET/Frontend/assets/146813902/767595b3-f168-4a2d-9a21-7d9452900f3c)

**Comment by kseniia2673** [comment]
Если необходимо, разобьем на подзадачи по фичам. Напрмер, пагинация и превью - одна задача, фильтры - другая @Julia-Papina

**Comment by Julia-Papina** [comment]
Выполнено
