### ISSUE TITLE
Разработать фичу LK.4.2 LK.4.2.2  Изменение пароля 

### ISSUE THREAD

**Issue by kseniia2673** [Pet-projects-CodePET/Frontend#64]
Эта задача также включает в себя логику изменения пароля и удаления аккаунта. При необходимости, можем разбить на 2 задачи
![2024-04-08_11-59-09](https://github.com/Pet-projects-CodePET/Frontend/assets/118973229/3f1e823b-3a1e-4c65-b4d0-b83a07122d4f)

**Comment by Julia-Papina** [comment]
Изменение пароля - @Julia-Papina

**Comment by Julia-Papina** [comment]
Выполнено
