### ISSUE TITLE
Создать структуру папок в репозитории (FSD архитектура)

### ISSUE THREAD

**Issue by Julia-Papina** [Pet-projects-CodePET/Frontend#7]
- [x] Создать структуру папок в репозитории

**Comment by Julia-Papina** [comment]
Создать структуру папок в репозитории - @Liolikmolo

**Comment by Liolikmolo** [comment]
Папки соответствуют архитектуре FSD. Все файлы, которые размещены внутри папок - для примера, чтобы понять суть архитектуры. Файлы/папки (кроме корневых) можно изменять, дополнять при необходимости
