### ISSUE TITLE
Разработать фичу LK.4.2, LK.4.2.1 Редактирование профиля пользователя - Текстовый редактор "О себе"

### ISSUE THREAD

**Issue by Julia-Papina** [Pet-projects-CodePET/Frontend#75]
Подключить библиотеку с текстовым редактором в поле "О себе"
![2024-02-26_09-13-40](https://github.com/Pet-projects-CodePET/Frontend/assets/118973229/8ed3fe40-a3a3-4d95-b17f-66cb2551b52d)

**Comment by kseniia2673** [comment]
к среде жду готовую задачу @vvkon13
